// Code generated by "enumer -type GeofenceType -trimprefix GeofenceType -json -text -sql:int geofence.go"; DO NOT EDIT.

package model

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
)

const _GeofenceTypeName = "UnknownCirclePolygonRectangle"

var _GeofenceTypeIndex = [...]uint8{0, 7, 13, 20, 29}

const _GeofenceTypeLowerName = "unknowncirclepolygonrectangle"

func (i GeofenceType) String() string {
	if i < 0 || i >= GeofenceType(len(_GeofenceTypeIndex)-1) {
		return fmt.Sprintf("GeofenceType(%d)", i)
	}
	return _GeofenceTypeName[_GeofenceTypeIndex[i]:_GeofenceTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _GeofenceTypeNoOp() {
	var x [1]struct{}
	_ = x[GeofenceTypeUnknown-(0)]
	_ = x[GeofenceTypeCircle-(1)]
	_ = x[GeofenceTypePolygon-(2)]
	_ = x[GeofenceTypeRectangle-(3)]
}

var _GeofenceTypeValues = []GeofenceType{GeofenceTypeUnknown, GeofenceTypeCircle, GeofenceTypePolygon, GeofenceTypeRectangle}

var _GeofenceTypeNameToValueMap = map[string]GeofenceType{
	_GeofenceTypeName[0:7]:        GeofenceTypeUnknown,
	_GeofenceTypeLowerName[0:7]:   GeofenceTypeUnknown,
	_GeofenceTypeName[7:13]:       GeofenceTypeCircle,
	_GeofenceTypeLowerName[7:13]:  GeofenceTypeCircle,
	_GeofenceTypeName[13:20]:      GeofenceTypePolygon,
	_GeofenceTypeLowerName[13:20]: GeofenceTypePolygon,
	_GeofenceTypeName[20:29]:      GeofenceTypeRectangle,
	_GeofenceTypeLowerName[20:29]: GeofenceTypeRectangle,
}

var _GeofenceTypeNames = []string{
	_GeofenceTypeName[0:7],
	_GeofenceTypeName[7:13],
	_GeofenceTypeName[13:20],
	_GeofenceTypeName[20:29],
}

// GeofenceTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func GeofenceTypeString(s string) (GeofenceType, error) {
	if val, ok := _GeofenceTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _GeofenceTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to GeofenceType values", s)
}

// GeofenceTypeValues returns all values of the enum
func GeofenceTypeValues() []GeofenceType {
	return _GeofenceTypeValues
}

// GeofenceTypeStrings returns a slice of all String values of the enum
func GeofenceTypeStrings() []string {
	strs := make([]string, len(_GeofenceTypeNames))
	copy(strs, _GeofenceTypeNames)
	return strs
}

// IsAGeofenceType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i GeofenceType) IsAGeofenceType() bool {
	for _, v := range _GeofenceTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for GeofenceType
func (i GeofenceType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for GeofenceType
func (i *GeofenceType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("GeofenceType should be a string, got %s", data)
	}

	var err error
	*i, err = GeofenceTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for GeofenceType
func (i GeofenceType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for GeofenceType
func (i *GeofenceType) UnmarshalText(text []byte) error {
	var err error
	*i, err = GeofenceTypeString(string(text))
	return err
}

func (i GeofenceType) Value() (driver.Value, error) {
	return int64(i), nil
}

func (i *GeofenceType) Scan(value any) error {
	if value == nil {
		return nil
	}

	switch v := value.(type) {
	case int64:
		*i = GeofenceType(v)
		return nil
	case int32:
		*i = GeofenceType(v)
		return nil
	case int:
		*i = GeofenceType(v)
		return nil
	case float64:
		*i = GeofenceType(int64(v))
		return nil
	case float32:
		*i = GeofenceType(int64(v))
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of GeofenceType: %[1]T(%[1]v)", value)
	}

	if n, err := strconv.ParseInt(strings.TrimSpace(str), 10, 64); err == nil {
		*i = GeofenceType(n)
		return nil
	}

	val, err := GeofenceTypeString(str)
	if err != nil {
		return err
	}
	*i = val
	return nil
}
