// Code generated by "enumer -type GeofenceStatus -trimprefix GeofenceStatus -transform lower -json -text -sql:int geofence.go"; DO NOT EDIT.

package model

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
)

const _GeofenceStatusName = "unknownactiveinactivearchiveddeleted"

var _GeofenceStatusIndex = [...]uint8{0, 7, 13, 21, 29, 36}

const _GeofenceStatusLowerName = "unknownactiveinactivearchiveddeleted"

func (i GeofenceStatus) String() string {
	if i < 0 || i >= GeofenceStatus(len(_GeofenceStatusIndex)-1) {
		return fmt.Sprintf("GeofenceStatus(%d)", i)
	}
	return _GeofenceStatusName[_GeofenceStatusIndex[i]:_GeofenceStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _GeofenceStatusNoOp() {
	var x [1]struct{}
	_ = x[GeofenceStatusUnknown-(0)]
	_ = x[GeofenceStatusActive-(1)]
	_ = x[GeofenceStatusInactive-(2)]
	_ = x[GeofenceStatusArchived-(3)]
	_ = x[GeofenceStatusDeleted-(4)]
}

var _GeofenceStatusValues = []GeofenceStatus{GeofenceStatusUnknown, GeofenceStatusActive, GeofenceStatusInactive, GeofenceStatusArchived, GeofenceStatusDeleted}

var _GeofenceStatusNameToValueMap = map[string]GeofenceStatus{
	_GeofenceStatusName[0:7]:        GeofenceStatusUnknown,
	_GeofenceStatusLowerName[0:7]:   GeofenceStatusUnknown,
	_GeofenceStatusName[7:13]:       GeofenceStatusActive,
	_GeofenceStatusLowerName[7:13]:  GeofenceStatusActive,
	_GeofenceStatusName[13:21]:      GeofenceStatusInactive,
	_GeofenceStatusLowerName[13:21]: GeofenceStatusInactive,
	_GeofenceStatusName[21:29]:      GeofenceStatusArchived,
	_GeofenceStatusLowerName[21:29]: GeofenceStatusArchived,
	_GeofenceStatusName[29:36]:      GeofenceStatusDeleted,
	_GeofenceStatusLowerName[29:36]: GeofenceStatusDeleted,
}

var _GeofenceStatusNames = []string{
	_GeofenceStatusName[0:7],
	_GeofenceStatusName[7:13],
	_GeofenceStatusName[13:21],
	_GeofenceStatusName[21:29],
	_GeofenceStatusName[29:36],
}

// GeofenceStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func GeofenceStatusString(s string) (GeofenceStatus, error) {
	if val, ok := _GeofenceStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _GeofenceStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to GeofenceStatus values", s)
}

// GeofenceStatusValues returns all values of the enum
func GeofenceStatusValues() []GeofenceStatus {
	return _GeofenceStatusValues
}

// GeofenceStatusStrings returns a slice of all String values of the enum
func GeofenceStatusStrings() []string {
	strs := make([]string, len(_GeofenceStatusNames))
	copy(strs, _GeofenceStatusNames)
	return strs
}

// IsAGeofenceStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i GeofenceStatus) IsAGeofenceStatus() bool {
	for _, v := range _GeofenceStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for GeofenceStatus
func (i GeofenceStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for GeofenceStatus
func (i *GeofenceStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("GeofenceStatus should be a string, got %s", data)
	}

	var err error
	*i, err = GeofenceStatusString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for GeofenceStatus
func (i GeofenceStatus) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for GeofenceStatus
func (i *GeofenceStatus) UnmarshalText(text []byte) error {
	var err error
	*i, err = GeofenceStatusString(string(text))
	return err
}

func (i GeofenceStatus) Value() (driver.Value, error) {
	return int64(i), nil
}

func (i *GeofenceStatus) Scan(value any) error {
	if value == nil {
		return nil
	}

	switch v := value.(type) {
	case int64:
		*i = GeofenceStatus(v)
		return nil
	case int32:
		*i = GeofenceStatus(v)
		return nil
	case int:
		*i = GeofenceStatus(v)
		return nil
	case float64:
		*i = GeofenceStatus(int64(v))
		return nil
	case float32:
		*i = GeofenceStatus(int64(v))
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of GeofenceStatus: %[1]T(%[1]v)", value)
	}

	if n, err := strconv.ParseInt(strings.TrimSpace(str), 10, 64); err == nil {
		*i = GeofenceStatus(n)
		return nil
	}

	val, err := GeofenceStatusString(str)
	if err != nil {
		return err
	}
	*i = val
	return nil
}
